### ISSUE TITLE
IsHorizontal property is not effect 

### ISSUE THREAD

**Issue by caothuong** [Binwell/FastGrid#2]
I try using it with FastGridSample in this source but it did not run on andoird:

![image](https://user-images.githubusercontent.com/7591690/52686534-bcb7eb00-2f80-11e9-944f-99ad3a13c01f.png)

![image](https://user-images.githubusercontent.com/7591690/52686561-deb16d80-2f80-11e9-835e-fe58ab7d9533.png)

**Comment by SlavaChernikoff** [comment]
Fixed by [https://github.com/Binwell/FastGrid/pull/4](https://github.com/Binwell/FastGrid/pull/4) 
Closed.
