### ISSUE TITLE
How can i add the horizontal scrolling in viewcell type X?

### ISSUE THREAD

**Issue by rex232** [Binwell/FastGrid#3]
Any sample or advise? thanks

**Comment by nakazanie-ton** [comment]
You can just put a scrollview inside a view (for example, bindablelayout) of viewcell and set its width to screensize width. You should be able to scroll the content of viewcell then.

**Comment by SlavaChernikoff** [comment]
Fixed by [https://github.com/Binwell/FastGrid/pull/4](https://github.com/Binwell/FastGrid/pull/4) 
Closed.
